### PR TITLE
Added all the automation and workflows, and simplified yaml

### PR DESCRIPTION
**Pull request by soumyaDghosh**
Need to rename the master branch to candidate branch.

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
Branch has been renamed! Can you also add the PR build action?

**Comment by soumyaDghosh** [comment]
Isn't it there named `pull-request.yml`?

**Comment by merlijn-sebrechts** [comment]
Huh, indeed! I wonder why it's not executing here.

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

**Pull request merged**
