### PR TITLE
Add missing stage packages

### PR DESCRIPTION
**Pull request by om26er**
* Fixes a warning during build time
* We should probably land this but *not* promote a new release based on this change

### CODE REVIEW

**Comment by popey** [comment]
Sorry for the delay @om26er - Is this still required?

**Comment by om26er** [comment]
The proposed change as  understand does nothing, we'd need to export an environment variable (LD_LIBRARY_PATH) so that the snap could actually "see" those new libraries.

**Comment by popey** [comment]
I don't think that should be necessary given they're staged packages from the archive so they will have the LD library path set as they'll end up in the typical places inside the snap.

**Comment by om26er** [comment]
> I don't think that should be necessary given they're staged packages from the archive so they will have the LD library path set as they'll end up in the typical places inside the snap.

In that cases, lets land this.

**Pull request closed without merging**
