### PR TITLE
Various Changes in the sync process

### LINKED ISSUE #110: [Snap store page] Please tell us the animal names
### What changes would you like?

When I go to the snap store and look at "Channel", I see the offered version is "latest/stable 2022.3.1.20". 
Problem: I don't know what that is! The Android developers I know, we do not call Android versions by their version numbers. We call them by their codenames, which are all animals.

[](https://github.com/snapcrafters/android-studio/assets/277318/cd7f232c-be50-4050-a387-a5ca52fc002a)

On my project we have an agreement that we are currently using Flamingo. What version number is that? I don't know. On Windows I open the Jetbrains Toolbox app and in the list of IDEs to download "Flamingo 2022.2.1 Patch 1". I know it sounds silly but it really does say"Flamingo" in the downloader. And it is easier to remember the name "Flamingo" than the number 2022.2.

I recommend you explain, ideally in the channel name/channel popup menu but if not there in the description, what the "animal name" of the release we are about to download is.

Screenshot (expected behavior: animals. observed behavior: no animals ☹) :
image

### Any extra information?

It would also be nice to [do as suggested here](https://github.com/snapcrafters/android-studio/issues/43) and offer more than one "animal" at a time.  You installed Giraffe so this may actually create a problem when I edit our Flamingo project. I might have to be careful not to check my Giraffe-updated project files into git.

### PR DESCRIPTION
**Pull request by soumyaDghosh**
1. Remove the need of a python file to fetch the version, url
2. Added codename into the version (closes #110 )

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
I wonder, android studio has an internal update checker. Is there any way to find out what URL that uses? Maybe we could use the same url instead of these oneliners

**Comment by soumyaDghosh** [comment]
@merlijn-sebrechts 

image


It's showing that the updates are managed by Snap.

**Comment by merlijn-sebrechts** [comment]
can you update your PR to get the latest update version and name from `https://dl.google.com/android/studio/patches/updates.xml`?
 
This is what the app uses when installed without snap, so this will be long-term stable. You just need to parse the XML.
should be easy to get it from this tag: `      <build apiVersion="AI-231.9392.1" number="AI-231.9392.1.2311.11076708" version="Hedgehog | 2023.1.1">`

**Comment by soumyaDghosh** [comment]
> can you update your PR to get the latest update version and name from `https://dl.google.com/android/studio/patches/updates.xml`?

This url doesn't show the actual version number and the url to download. I'd still need to have a separate url to get the actual version number which is currently **`2023.1.1.26`**

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

Let's get this running now, and try to find a better way to get the version in the future.

**Comment by merlijn-sebrechts** [comment]
@soumyaDghosh seems like there is still an issue in the process: https://github.com/snapcrafters/android-studio/actions/runs/7193616466/job/19592441198

**Comment by soumyaDghosh** [comment]
I have been looking into it from yesterday. And what I am thinking is, the url has `/` in it, which is probably confusing the `sed` command. I can't found any answer for it other than this. 

EDIT: I can confirm this now.

**Comment by soumyaDghosh** [comment]
Temporarily.. should we shift to `yq`?

**Comment by merlijn-sebrechts** [comment]
Sure!

**Comment by jnsgruk** [comment]
I commented on #120, but `sed` can be used with any separator to get around this, so you can do:

`sed -i 's|foo|bar'` or `sed -i 's#foo#bar'` etc.

**Pull request merged**
