### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by om26er**
New upstream release 3.2.1

### CODE REVIEW

**Comment by popey** [comment]
It [built](https://launchpad.net/~build.snapcraft.io/+snap/125825f60ca4a81dbf25024d40e45f87-xenial/+build/352233) but is taking a very long time to upload to the store.

image

I assume it'll be finished by the morning, so I'll grab coffee, test and promote then :) Thanks again @om26er

**Comment by popey** [comment]
Looks like a [bug](https://bugs.launchpad.net/launchpad-buildd/+bug/1797685)

**Comment by popey** [comment]
Triggered again...

**Comment by om26er** [comment]
@popey seems it worked this time, I see 3.2.1 in the edge channel.

**Comment by popey** [comment]
Yup, tested and released to stable. Thanks @om26er

**Pull request merged**
